### ISSUE TITLE
Crash when generating a world　1.20.1

### ISSUE THREAD

**Issue by nefertus** [CravenCraft/EpicParagliders#28]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2024-01-20 21:39:32
Description: Unexpected error

java.lang.NoSuchMethodError: 'int yesman.epicfight.api.utils.ExtendableEnumManager.assign(java.lang.Object)'
	at net.cravencraft.epicparagliders.gameasset.ExhaustionMotions.<init>(ExhaustionMotions.java:26) ~[epicparagliders-0.6.0-1.20.1.jar%23160!/:0.6.0-1.20.1] {re:mixin,re:classloading}
	at net.cravencraft.epicparagliders.gameasset.ExhaustionMotions.<clinit>(ExhaustionMotions.java:6) ~[epicparagliders-0.6.0-1.20.1.jar%23160!/:0.6.0-1.20.1] {re:mixin,re:classloading}
	at yesman.epicfight.world.capabilities.entitypatch.player.PlayerPatch.handler$zzf000$addExhaustionAnimations(PlayerPatch.java:672) ~[EpicFight-20.6.3.jar%23159!/:20.6.3] {re:mixin,re:classloading,pl:mixin:APP:epicparagliders.mixins.json:epicfight.capabilities.PlayerPatchMixin,pl:mixin:A}
	at yesman.epicfight.world.capabilities.entitypatch.player.PlayerPatch.initAnimator(PlayerPatch.java) ~[EpicFight-20.6.3.jar%23159!/:20.6.3] {re:mixin,re:classloading,pl:mixin:APP:epicparagliders.mixins.json:epicfight.capabilities.PlayerPatchMixin,pl:mixin:A}
	at yesman.epicfight.api.client.animation.ClientAnimator.init(ClientAnimator.java:132) ~[EpicFight-20.6.3.jar%23159!/:20.6.3] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:epicparagliders.mixins.json:epicfight.client.ClientAnimatorMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at yesman.epicfight.world.capabilities.entitypatch.LivingEntityPatch.onConstructed(LivingEntityPatch.java:92) ~[EpicFight-20.6.3.jar%23159!/:20.6.3] {re:mixin,re:classloading}
	at yesman.epicfight.world.capabilities.entitypatch.player.PlayerPatch.onConstructed(PlayerPatch.java:71) ~[EpicFight-20.6.3.jar%23159!/:20.6.3] {re:mixin,re:classloading,pl:mixin:APP:epicparagliders.mixins.json:epicfight.capabilities.PlayerPatchMixin,pl:mixin:A}
	at yesman.epicfight.client.world.capabilites.entitypatch.player.LocalPlayerPatch.onConstructed(LocalPlayerPatch.java:60) ~[EpicFight-20.6.3.jar%23159!/:20.6.3] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:epicparagliders.mixins.json:epicfight.client.LocalPlayerPatchMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at yesman.epicfight.client.world.capabilites.entitypatch.player.LocalPlayerPatch.onConstructed(LocalPlayerPatch.java:44) ~[EpicFight-20.6.3.jar%23159!/:20.6.3] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:epicparagliders.mixins.json:epicfight.client.LocalPlayerPatchMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at yesman.epicfight.events.CapabilityEvent.attachEntityCapability(CapabilityEvent.java:41) ~[EpicFight-20.6.3.jar%23159!/:20.6.3] {re:classloading}
	at yesman.epicfight.events.__CapabilityEvent_attachEntityCapability_AttachCapabilitiesEvent.invoke(.dynamic) ~[EpicFight-20.6.3.jar%23159!/:20.6.3] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:623) ~[forge-1.20.1-47.2.20-universal.jar%23167!/:?] {re:mixin,re:classloading}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:617) ~[forge-1.20.1-47.2.20-universal.jar%23167!/:?] {re:mixin,re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.doGatherCapabilities(CapabilityProvider.java:72) ~[forge-1.20.1-47.2.20-universal.jar%23167!/:?] {re:classloading,re:mixin}
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:67) ~[forge-1.20.1-47.2.20-universal.jar%23167!/:?] {re:classloading,re:mixin}
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:51) ~[forge-1.20.1-47.2.20-universal.jar%23167!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.entity.Entity.<init>(Entity.java:265) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.entity.LivingEntity.<init>(LivingEntity.java:233) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:epicfight.mixins.json:MixinLivingEntity,pl:mixin:A}
	at net.minecraft.world.entity.player.Player.<init>(Player.java:177) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:paraglider.mixins.json:MixinPlayer,pl:mixin:APP:epicfight.mixins.json:MixinPlayer,pl:mixin:A}
	at net.minecraft.client.player.AbstractClientPlayer.<init>(AbstractClientPlayer.java:41) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.player.LocalPlayer.<init>(LocalPlayer.java:141) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:epicfight.mixins.json:MixinLocalPlayer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105250_(MultiPlayerGameMode.java:389) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105246_(MultiPlayerGameMode.java:385) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5998_(ClientPacketListener.java:406) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.network.protocol.game.ClientboundLoginPacket.m_5797_(ClientboundLoginPacket.java:95) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundLoginPacket.m_5797_(ClientboundLoginPacket.java:25) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.2.20.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.20.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.20.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.20.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: 
	Epic Fight (epicfight), Version: 20.6.3
		at TRANSFORMER/epicfight@20.6.3/yesman.epicfight.world.capabilities.entitypatch.player.PlayerPatch.handler$zzf000$addExhaustionAnimations(PlayerPatch.java:672)

	Epic Paragliders Mod (epicparagliders), Version: 0.6.0-1.20.1
		at TRANSFORMER/epicparagliders@0.6.0-1.20.1/net.cravencraft.epicparagliders.gameasset.ExhaustionMotions.<init>(ExhaustionMotions.java:26)
Stacktrace:
	at net.cravencraft.epicparagliders.gameasset.ExhaustionMotions.<init>(ExhaustionMotions.java:26) ~[epicparagliders-0.6.0-1.20.1.jar%23160!/:0.6.0-1.20.1] {re:mixin,re:classloading}
	at net.cravencraft.epicparagliders.gameasset.ExhaustionMotions.<clinit>(ExhaustionMotions.java:6) ~[epicparagliders-0.6.0-1.20.1.jar%23160!/:0.6.0-1.20.1] {re:mixin,re:classloading}
	at yesman.epicfight.world.capabilities.entitypatch.player.PlayerPatch.handler$zzf000$addExhaustionAnimations(PlayerPatch.java:672) ~[EpicFight-20.6.3.jar%23159!/:20.6.3] {re:mixin,re:classloading,pl:mixin:APP:epicparagliders.mixins.json:epicfight.capabilities.PlayerPatchMixin,pl:mixin:A}
	at yesman.epicfight.world.capabilities.entitypatch.player.PlayerPatch.initAnimator(PlayerPatch.java) ~[EpicFight-20.6.3.jar%23159!/:20.6.3] {re:mixin,re:classloading,pl:mixin:APP:epicparagliders.mixins.json:epicfight.capabilities.PlayerPatchMixin,pl:mixin:A}
	at yesman.epicfight.api.client.animation.ClientAnimator.init(ClientAnimator.java:132) ~[EpicFight-20.6.3.jar%23159!/:20.6.3] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:epicparagliders.mixins.json:epicfight.client.ClientAnimatorMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at yesman.epicfight.world.capabilities.entitypatch.LivingEntityPatch.onConstructed(LivingEntityPatch.java:92) ~[EpicFight-20.6.3.jar%23159!/:20.6.3] {re:mixin,re:classloading}
	at yesman.epicfight.world.capabilities.entitypatch.player.PlayerPatch.onConstructed(PlayerPatch.java:71) ~[EpicFight-20.6.3.jar%23159!/:20.6.3] {re:mixin,re:classloading,pl:mixin:APP:epicparagliders.mixins.json:epicfight.capabilities.PlayerPatchMixin,pl:mixin:A}
	at yesman.epicfight.client.world.capabilites.entitypatch.player.LocalPlayerPatch.onConstructed(LocalPlayerPatch.java:60) ~[EpicFight-20.6.3.jar%23159!/:20.6.3] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:epicparagliders.mixins.json:epicfight.client.LocalPlayerPatchMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at yesman.epicfight.client.world.capabilites.entitypatch.player.LocalPlayerPatch.onConstructed(LocalPlayerPatch.java:44) ~[EpicFight-20.6.3.jar%23159!/:20.6.3] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:epicparagliders.mixins.json:epicfight.client.LocalPlayerPatchMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at yesman.epicfight.events.CapabilityEvent.attachEntityCapability(CapabilityEvent.java:41) ~[EpicFight-20.6.3.jar%23159!/:20.6.3] {re:classloading}
	at yesman.epicfight.events.__CapabilityEvent_attachEntityCapability_AttachCapabilitiesEvent.invoke(.dynamic) ~[EpicFight-20.6.3.jar%23159!/:20.6.3] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:623) ~[forge-1.20.1-47.2.20-universal.jar%23167!/:?] {re:mixin,re:classloading}
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:617) ~[forge-1.20.1-47.2.20-universal.jar%23167!/:?] {re:mixin,re:classloading}
	at net.minecraftforge.common.capabilities.CapabilityProvider.doGatherCapabilities(CapabilityProvider.java:72) ~[forge-1.20.1-47.2.20-universal.jar%23167!/:?] {re:classloading,re:mixin}
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:67) ~[forge-1.20.1-47.2.20-universal.jar%23167!/:?] {re:classloading,re:mixin}
	at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:51) ~[forge-1.20.1-47.2.20-universal.jar%23167!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.entity.Entity.<init>(Entity.java:265) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.entity.LivingEntity.<init>(LivingEntity.java:233) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:epicfight.mixins.json:MixinLivingEntity,pl:mixin:A}
	at net.minecraft.world.entity.player.Player.<init>(Player.java:177) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:paraglider.mixins.json:MixinPlayer,pl:mixin:APP:epicfight.mixins.json:MixinPlayer,pl:mixin:A}
	at net.minecraft.client.player.AbstractClientPlayer.<init>(AbstractClientPlayer.java:41) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.player.LocalPlayer.<init>(LocalPlayer.java:141) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:epicfight.mixins.json:MixinLocalPlayer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105250_(MultiPlayerGameMode.java:389) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_105246_(MultiPlayerGameMode.java:385) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5998_(ClientPacketListener.java:406) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.network.protocol.game.ClientboundLoginPacket.m_5797_(ClientboundLoginPacket.java:95) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundLoginPacket.m_5797_(ClientboundLoginPacket.java:25) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 961, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 0 game time, 0 day time
	Server brand: ~~ERROR~~ NullPointerException: Cannot invoke "net.minecraft.client.player.LocalPlayer.m_108629_()" because "this.f_104565_.f_91074_" is null
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:455) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2319) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:740) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.2.20.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.20.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.20.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.20.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, mod_resources

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 14624327504 bytes (13946 MiB) / 17179869184 bytes (16384 MiB) up to 17179869184 bytes (16384 MiB)
	CPUs: 24
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i7-13700F
	Identifier: Intel64 Family 6 Model 183 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.11
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce RTX 4060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2803
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3667
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 41238.04
	Virtual memory used (MB): 35824.58
	Swap memory total (MB): 8630.93
	Swap memory used (MB): 160.64
	JVM Flags: 12 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx25472m -Xms256m -Xms16G -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=30 -XX:G1HeapRegionSize=32M
	Launched Version: forge-47.2.20
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce RTX 4060 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 536.67, NVIDIA Corporation
	Window size: 1664x936
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: en_us
	CPU: 24x 13th Gen Intel(R) Core(TM) i7-13700F
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Xx_StrongPVP_xX'/225, l='ServerLevel[New World]', x=6.50, y=65.00, z=-0.50]]
	Data Packs: vanilla, mod:paraglider (incompatible), mod:forge, mod:epicparagliders (incompatible), mod:epicfight (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.20.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.20.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.20.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.20.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.20.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		Paraglider-forge-20.1.3.jar                       |Paraglider                    |paraglider                    |20.1.3              |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.2.20-universal.jar                |Forge                         |forge                         |47.2.20             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		epicparagliders-0.6.0-1.20.1.jar                  |Epic Paragliders Mod          |epicparagliders               |0.6.0-1.20.1        |DONE      |Manifest: NOSIGNATURE
		EpicFight-20.6.3.jar                              |Epic Fight                    |epicfight                     |20.6.3              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 97440184-f7a4-4f69-b677-1d1443db3002
	FML: 47.2
	Forge: net.minecraftforge:47.2.20

**Comment by CravenCraft** [comment]
Epic Fight had several new updates this past year, which made my mod incompatible with it. Just updated it, and it should be released on CurseForge shortly.
